### ISSUE TITLE
"Likes" feature

### ISSUE THREAD

**Issue by hmans** [hmans/pants#19]
Allow users to "like" posts. (A note about terminology: from "like", "fav" and "star", "like" is the one that simply works best for me, since you're expressing that you _like_ a piece of content, and also since it's such a well-known activity, thanks to Facebook. "Fav" and "star" imply that you're marking something as a "favorite" or more important, which doesn't make a lot of sense in a social context. I was considering going with something more playful like "cheer", but once again, just the prevalence of "like" makes it the clear winner.)

The "Like" feature on #pants is interesting, as it also adds support for multiple different post types, with Likes simply being a different post type from normale text posts. When you Like something, what really happens behind the scenes is that you create a new post (of the new `pants.like` type), which is transferred to the liked content's owner via the same mechanism that otherwise transfers normal posts. `pants.like` posts are, of course, rendered in an entirely different fashion from normal posts.

**Do this first:**
- [ ] Rewrite WebmentionHandler to do the following:
  - [ ] Find the link linking to `target` and analyze its attributes _before_ deciding how to deal with the webmention
  - [ ] If `source` is a 404, delete existing posts and trash existing pings
- [ ] Teach Pings to store additional microformat data; give them a `type` (like, mention, ...) for indieweb like/etc. tracking

**Tasks:**
- [x] Add a "Like" button to posts that, when clicked, creates a new `pants.like` post referencing the liked post
- [x] Prevent a user from creating multiple likes for the same post
- [x] Notify the liked post's site about the new `pants.like` post via webmention
- [x] When rendering a post, render its received likes
- [ ] Deal with incoming non-#pants likes. (Store likes in their own model/column, after all?)
- [ ] After unliking a post (= deleting the `pants.like` post), send another webmention to notify the OP
- [ ] Ajaxify like/unlike actions
- [ ] Use correct microformat when rendering a `pants.like`

**Like counts:**
- [x] Add `number_of_likes` column.
- [x] Render number of likes in post partial.
- [x] Update `number_of_likes` in `Post#before_save` callback.
- [x] Serve `number_of_likes` in post JSON.
- [x] Read `number_of_likes` from post JSON.

**Cleanup/Polish:**
- [x] Teach the network timeline to render likes notification-style (well, whatever this means)
- [ ] Render Likes as a facepile?
- [x] Teach the blog (and ATOM feed) to only render `pants.post` posts
- [ ] Smarten up "Replies" rendering
- [ ] Nicer post action buttons/links
- [ ] Figure out how to fix the Incoming Timeline (maybe better unified post actions?)
